### PR TITLE
Removed OR clause for non-load commanding

### PR DESCRIPTION
**Pull request by jzuhone**
I have deleted the OR clause for non-load commanding, as in the other thermal model check tools.

### CODE REVIEW

**Comment by Gregg140** [comment]
What loads did you test the model on?

**Comment by jzuhone** [comment]
@Gregg140 I haven't tested it yet--I just wanted to get it up here. We shouldn't merge until I test.

**Comment by Gregg140** [comment]
Ah ok. I'm testing before merging....I was wondering how you guys got it up there so fast :)

**Comment by jzuhone** [comment]
I have tested on the loads FEB2017, FEB2717, MAR0617, and MAR1317 as well, and the prediction and validation outputs agree.

**Comment by jzuhone** [comment]
closing this PR because the issue has been resolved in `acis_thermal_check`.

**Comment by jeanconn** [comment]
Hi @jzuhone I could actually use a reminder on how this was handled in `acis_thermal_check` at some point.  Non-urgent.

**Comment by jzuhone** [comment]
@jeanconn (short version) what we ended up doing was only removing the OR clause for interrupt loads

**Comment by jeanconn** [comment]
Thanks!  That makes sense, and the record of that in this PR will help if I come back to this issue.

**Pull request closed without merging**
